### ISSUE TITLE
support DOH & DOT

### ISSUE THREAD

**Issue by hozansahin** [pommee/goaway#43]
**Is your feature request related to a problem? Please describe.**
No, this is not a problem, it is a feature request.

**Describe the solution you'd like**
I think that adding DoH and DoT [DNS-over-TLS](https://en.wikipedia.org/wiki/DNS_over_TLS) as well as [DNS-over-QUIC](https://datatracker.ietf.org/doc/html/rfc9250) support upstream would be more efficient and better.

**Describe alternatives you've considered**
All of these features are available in AdGuard Home, which is a more advanced version. [Learn more](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#upstreams) about configuring upstream DNS servers
<img width="1118" height="493" alt="Image" src="https://github.com/user-attachments/assets/b7a8d982-c403-4050-874a-59866a4704dd" />

**Additional context**

<img width="1856" height="908" alt="Image" src="https://github.com/user-attachments/assets/ad7c3252-cf3d-43dd-ba76-66081e92b2b4" />

**Comment by pommee** [comment]
@hozansahin This is a feature request I have written down as it has been requested a couple of times. Will keep the issue open so as it is not currently visible to others.  

Will update once progress has been made.

**Comment by pommee** [comment]
@hozansahin I just released [v0.58.0](https://github.com/pommee/goaway/releases/tag/v0.58.0) which adds support for DoT. Please give it a go and tell me what you think. Refer to the updated README and the default `settings.yaml` for setup. 

Will look into DoH at a later point.

**Comment by hozansahin** [comment]
> [@hozansahin](https://github.com/hozansahin) I just released [v0.58.0](https://github.com/pommee/goaway/releases/tag/v0.58.0) which adds support for DoT. Please give it a go and tell me what you think. Refer to the updated README and the default `settings.yaml` for setup.
> 
> Will look into DoH at a later point.

yes, work is fine, but accepts connections entered with Regular UDP ip address. It does not accept when I enter custom addresses given with 
domain. 
I guess there is no DoH support yet

<img width="443" height="258" alt="Image" src="https://github.com/user-attachments/assets/15ecd94b-7362-4793-be6d-8e6b6cb9a8d7" />

**Comment by pommee** [comment]
@hozansahin You seem to have an invalid IPv4 address. And no, DoH is not yet implemented; to quote myself - "Will look into DoH at a later point."

**Comment by pommee** [comment]
@hozansahin Both DoT and DoH are now implemented. You will need to generate a certificate to use (as you do for Pi-Hole and AdGuardHome) and expose the correct ports if you are running inside of a container.

**Comment by hozansahin** [comment]
> [@hozansahin](https://github.com/hozansahin) Both DoT and DoH are now implemented. You will need to generate a certificate to use (as you do for Pi-Hole and AdGuardHome) and expose the correct ports if you are running inside of a container.

Good job! but it still does not accept the dns format entered as follows, I can identify the ip address and ports but I am not sure if it is using DoT or DoH. the DNS Ping: Failed (dns) error still appears even though I entered a valid ipv4 address

<img width="407" height="97" alt="Image" src="https://github.com/user-attachments/assets/5948616f-0fc6-4db4-9d5d-fa8052997620" />

<img width="814" height="389" alt="Image" src="https://github.com/user-attachments/assets/6546d7c9-ee69-4502-bd95-b0beab711b22" />

**Comment by pommee** [comment]
@hozansahin This is the upstream ping logic that is faulty (forgot to update it). Though it should still work. For example the following works for me when testing:

```bash
# Gives the correct ip while using DoT
# Remove short and look in the bottom to verify that TLS is being used
dig @<server-ip> google.com. +tls +short

# Hexdump of the response given from using DoH
curl -k -H "Accept: application/dns-message" \
  "https://<server-ip>/dns-query?dns=AAABAAABAAAAAAAABmdvb2dsZQNjb20AAAEAAQ" \
  --output response.bin && \
  hexdump -C response.bin
```  

You can also see in the logs tab that a certain protocol has been used.

<img width="577" height="129" alt="Image" src="https://github.com/user-attachments/assets/1531c564-dd5f-407b-9083-e679003ffa4d" />

**Comment by hozansahin** [comment]
>You will need to generate a certificate to use (as you do for Pi-Hole and AdGuardHome) and expose the correct ports if you are running inside of a container.

hey @pommee 
I run goaway through Portainer as follows;

<img width="1603" height="861" alt="Image" src="https://github.com/user-attachments/assets/1f8417a9-d328-419e-88af-18c1c5a7204c" />

How do I need to do the compose file to enable SSL certificate , can you help me?

**Comment by pommee** [comment]
@hozansahin 

```yaml
services:
  goaway:
    image: pommee/goaway:latest
    container_name: goaway
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./cert.crt:/app/cert.crt  # Mount the certificate
      - ./key.key:/app/key.key    # And mount the key
    ...
```

Then in `settings.yaml` you also need to set both paths for `tlsCertFile & tlsKeyFile`.

**Comment by hozansahin** [comment]
> [@hozansahin](https://github.com/hozansahin)
> 
> services:
>   goaway:
>     image: pommee/goaway:latest
>     container_name: goaway
>     restart: unless-stopped
>     volumes:
>       - ./config:/app/config
>       - ./data:/app/data
>       - ./cert.crt:/app/cert.crt  # Mount the certificate
>       - ./key.key:/app/key.key    # And mount the key
>     ...
> Then in `settings.yaml` you also need to set both paths for `tlsCertFile & tlsKeyFile`.

thank you. actually I just wanted to ask how to get the SSL certificate. i am working locally in a homelab environment. i could not run TSL.

**Comment by pommee** [comment]
You would be better of searching for a guide on how to generate a certificate.  

**example**
```
openssl req -x509 -newkey rsa:2048 -keyout server.key -out server.crt -days 365 -nodes -subj "/CN=localhost"
```

**Comment by pommee** [comment]
Closing as the requested feature of DoT and DoH has been implemented.  

As a note, DNS-over-QUIC is planned for the future.
