### ISSUE TITLE
Bug: GoAway GUI will not start after reboot - Proxmox

### ISSUE THREAD

**Issue by KingHunter2019** [pommee/goaway#63]
**Describe the bug**
When rebooting GoAway, the GUI is inaccessible. The same goes for restoring a screenshot or a 

**To Reproduce**
1. Go to the Goaway container (created from Proxmox Helper Script)
2. Click on reboot, issue a command reboot, or restore a backup for a new container
3. Like any Virtual Machine or Container, the CLI will come up in Proxmox. — Totally Normal.
4. The **error begins** when you go back to the container GUI IP address (or domain from reverse proxy). It will not load.

**Expected behavior**
Getting back to the Default Interface.

<img width="1905" height="718" alt="Image" src="https://github.com/user-attachments/assets/e610215e-7c1e-4f1c-88b8-95dc86e6667f" />

**Screenshots & Logs**
See how a restored container, even with a different IP, will not show the Web GUI.

<img width="1579" height="952" alt="Image" src="https://github.com/user-attachments/assets/fb8245e8-5546-4841-be29-49e0f2306a71" />

**Please complete the following information:**
 - Platform: Proxmox version 8.4.14
 - LXC created from helper scripts: https://community-scripts.github.io/ProxmoxVE/scripts?id=goaway&category=Adblock+%26+DNS
 - GoAway Version: 0.62.6

**Comment by pommee** [comment]
Have you verified that the service is running after a reboot?  
`systemctl status goaway`  

What does the logs say?  
`cat /var/log/goaway.log`

**Comment by KingHunter2019** [comment]
> Have you verified that the service is running after a reboot? `systemctl status goaway`

I created a New Container for Testing. Please see below:

<img width="540" height="182" alt="Image" src="https://github.com/user-attachments/assets/4dc6d982-f87a-417a-b398-bde09447ef73" />

Able to Access CLI for Credentials:
<img width="1016" height="283" alt="Image" src="https://github.com/user-attachments/assets/c04fcbd0-ca24-4ae5-8efb-6182da5daa09" />

I tested some queries, looks good so far.

<img width="1915" height="951" alt="Image" src="https://github.com/user-attachments/assets/5cb6da37-6266-4fa8-a503-c65ecae0254f" />

Issued Reboot via CLI:

<img width="1058" height="682" alt="Image" src="https://github.com/user-attachments/assets/774dedd0-d0c4-4309-a51a-f29f46dd1cc6" />

After rebooting, the Page has gone blank:

<img width="1897" height="750" alt="Image" src="https://github.com/user-attachments/assets/49e2ff92-6c40-4e88-8842-0536bfe1033c" />

Command Issued: **systemctl status goaway**

<img width="838" height="267" alt="Image" src="https://github.com/user-attachments/assets/9225b2be-8581-4e72-aed8-774b104e488b" />


> What does the logs say? `cat /var/log/goaway.log`


Strangely, I get a few errors. I haven't added anything to it yet.
<img width="1399" height="601" alt="Image" src="https://github.com/user-attachments/assets/a849a132-d990-4ea8-903e-64868cc83875" />

**Comment by pommee** [comment]
Looks like the order of the log gets mangled for both of us once it has been restarted. Though I don't see the same behavior on my end. Runs fine after a reboot.  

Are you still able to make DNS queries after the reboot?

**Comment by KingHunter2019** [comment]
> Looks like the order of the log gets mangled for both of us once it has been restarted. Though I don't see the same behavior on my end. Runs fine after a reboot.

Ah, just my luck, Lol.

> Are you still able to make DNS queries after the reboot?

Yup, no issues there, thankfully.

**Comment by KingHunter2019** [comment]
> > Looks like the order of the log gets mangled for both of us once it has been restarted. Though I don't see the same behavior on my end. Runs fine after a reboot.
> 
> Ah, just my luck, Lol.
> 
> > Are you still able to make DNS queries after the reboot?
> 
> Yup, no issues there, thankfully.

I've found a solution; running a "systemctl restart goaway" allowed the GUI to return.


Log 1 (After using Reboot at CLI): 

<img width="1403" height="597" alt="Image" src="https://github.com/user-attachments/assets/8b6a41cf-82f5-4420-ab26-15453d8896a0" />

Log 2 (Issuing command: "systemctl restart goaway"): 
<img width="1389" height="602" alt="Image" src="https://github.com/user-attachments/assets/b60c7047-5ceb-4b03-a2ad-278f6d5dbecc" />

Log 2, starting at 13:28:12, confirms the issue was resolved because it successfully logs:

2025/09/30 13:28:12 [INFO] Web interface available at http://Go-Away-IP:8080 (In this case: 10.0.5.179)

The system was finally able to resolve its IP address as 10.0.5.179, allowing the application to complete its initialization and successfully announce the full address for the Web interface. This suggests the network had fully stabilized or the server was simply restarted after a minimal waiting period, allowing the IP to be correctly identified.

Given the [ERROR] Error getting IP address: server IP not found occurs, is there a way to implement a retry loop or a configurable delay before attempting the IP lookup? This could mitigate race conditions on systems where network interfaces initialize slowly.

**Comment by pommee** [comment]
Added some failover for this in [v0.62.9](https://github.com/pommee/goaway/releases/tag/v0.62.9). Should hopefully resolve the issue.

**Comment by nalexxx** [comment]
In v0.62.11 the issue still persists: the GUI is empty after an LXC reboot. Restarting the service fixes it.

**Comment by DannyFeliz** [comment]
I can confirm that the issue is still present in [v0.62.9](https://github.com/pommee/goaway/releases/tag/v0.62.9)

**Comment by pommee** [comment]
Noted. Will spend some time testing with an LXC container once the rewrite I am working on is finished.

**Comment by 0xDedSec42** [comment]
Google just lead me here, I've got the same issue with v0.62.20.
